export const arr2 = ["Light snow",
            "Moderate snow",
            "Heavy snow",
            "Patchy snow possible",
            "Blowing snow",
            "Patchy light snow",
            "Patchy moderate snow",
            "Ice pellets",
            "Light sleet showers",
            "Patchy sleet possible",
            "Moderate or heavy sleet",
            "Light sleet showers",
            "Patchy light snow with thunder",
            "Moderate or heavy sleet showers",
            "Light snow showers",
            "Moderate or heavy snow showers",
            "Light showers of ice pellets",
            "Moderate or heavy showers of ice pellets",
            "Moderate or heavy snow with thunder",
            "Blizzard","Sunny", "clear","Partly Cloudy", "Cloudy", "Overcast","Mist", "Fog", "Freezing fog","Thundery outbreaks possible",
            "Patchy light rain with thunder",
            "Moderate or heavy rain with thunder",
            "Heavy rain at times",
            "Moderate or heavy freezing rain","Moderate rain",
            "Rain",
            "Light rain",
            "Light rain shower",
            "Patchy rain nearby",
            "Patchy rain possible",
            "Patchy freezing drizzle possible",
            "Patchy light drizzle",
            "Light drizzle",
            "Freezing drizzle",
            "Heavy freezing drizzle",
            "Moderate or heavy rain shower",
            "Torrential rain shower",
        ]